# Generated by Django 5.2.8 on 2026-02-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sellers_city', to='sellers.city'),
        ),
    ]
