# Generated by Django 5.2.8 on 2026-04-22 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_seller'),
        ('sellers', '0005_alter_seller_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.city'),
        ),
    ]
