# Generated by Django 5.2.8 on 2026-02-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_exchange_fuel_car_exchange_car_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInvertory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField()),
                ('cars_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
